[package]
name = "funnyprint-render"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
imageproc.workspace = true
ab_glyph.workspace = true
funnyprint-proto = { path = "../funnyprint-proto" }
